name: CI Backend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build backend image
      run: docker build -t backend:${{ github.sha }} .

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: backend:${{ github.sha }}
        severity: HIGH,CRITICAL
        exit-code: 0

    - name: Setup Insecure Registry
      run: |
        echo "{\"insecure-registries\": [\"${{ secrets.REGISTRY_HOST }}\"]}" | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Push image
      run: |
        docker tag backend:${{ github.sha }} ${{ secrets.REGISTRY_HOST }}/backend:latest
        docker push ${{ secrets.REGISTRY_HOST }}/backend:latest
